# Sample Accelerate configuration for distributed training
# You can generate this file by running: accelerate config

compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU  # Change to NO for single GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16  # Can be 'no', 'fp16', or 'bf16'
num_machines: 1
num_processes: 2  # Number of GPUs to use
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false 